### ISSUE TITLE
csf model format

### ISSUE THREAD

**Issue by CBenghi** [nvpro-samples/gl_cadscene_rendertechniques#1]
Hello, 
Thanks for the great job on these repos.

I'd like to try some of the techniques you are presenting on 3D construction models coming from IFC and a little documentation would help me get it right first time.

Is there a set of specs of the CSF format that you can point me to?
In particular I'm not quite getting the relations between Geometry, Parts and Nodes.
The geforce model is a little complicated, a simple model with a few cubes would help reverse engineer the format in documentation absence (once I get it I'm happy to write some documentation for you, in case you are interested).

Any help is welcome.
Best,
Claudio

**Comment by pixeljetstream** [comment]
Hi,
there is no real spec, I created the format to have something simple for the sake of tech demos but representing how some CAD apps may organize data internally. The format is indirectly documented through the source code of the loader https://github.com/nvpro-samples/gl_cadscene_rendertechniques/blob/master/cadscenefile.h

A node can either reference geometry or not, it always has matrix information and all nodes are organized in a tree. If a node references geometry, it also contains the material assignments for each part. A single Geometry contains parts. Parts typically being model features like chamfers or joint surfaces and such as found in CAD apps.

**Comment by CBenghi** [comment]
I've looked at the header file and made sense of most of it.
What I'm still missing is how to interpret the fields of GeometryPart.

typedef struct _CSFGeometryPart {
    int     vertex;
    int     indexSolid;
    int     indexWire;
}

I was expecting to see some starting index (either solid or wire) and a the number of primitives in the part. Can you help?

**Comment by pixeljetstream** [comment]
it's the number of indices used in the part. The offsets are implicit by doing a prefix sum over all parts. vertex was supposed to be used for statistic or when not using indexbuffer values. However the design isn't great, clearly offset + number would have been better.
