### ISSUE TITLE
linux build issues

### ISSUE THREAD

**Issue by CapsAdmin** [nvpro-samples/gl_cadscene_rendertechniques#3]
in statesystem.cpp `memcmp` is used without `#include <cstring>`
in statesystem.cpp `__forceinline` is used directly
in cadscenefile.h there is `#define CSFAPI __declspec(dllexport)` which is windows specific
in nodetree.cpp `NULL` is used but I'm not sure what the solution here is other than using `0` since apparently `nullptr` is not supported in gcc

**Comment by pixeljetstream** [comment]
closing as linux is currently not supported
