### ISSUE TITLE
cmake file Build issue

### ISSUE THREAD

**Issue by viratgangurde** [nvpro-samples/gl_cadscene_rendertechniques#5]
Hi,
I am new learner and looking for to run this project.
I am making build using VS2015, by creating build folder under project folder 'gl_cadscene_rendertechniques-master/build'.
After building throwing below errors as listed,
CMake Error at CMakeLists.txt:21 (INCLUDE):
  include could not find load file:

```
E:/Vulkan API/Windows Example/gl_cadscene_rendertechniques-master/../shared_sources/CMakeLists_include.txt
```

CMake Error at CMakeLists.txt:22 (add_subdirectory):
  add_subdirectory given source "E:/Vulkan API/Windows
  Example/gl_cadscene_rendertechniques-master/../shared_sources" which is not
  an existing directory.

CMake Error at CMakeLists.txt:25 (_add_project_definitions):
  Unknown CMake command "_add_project_definitions".

Please help me to sort out.
Thanks in advanced.

**Comment by timmcintosh** [comment]
I'm experiencing the same problem. Can someone please explain what should be put in the shared resources? Thank you.

**Comment by CBenghi** [comment]
Hi guys, I think that the resources you want are available at:
https://github.com/nvpro-samples/shared_sources

I still get a failure to cmake after that, but I'll let you know if I found more.

Claudio

**Comment by CBenghi** [comment]
You also want the files at https://github.com/nvpro-samples/shared_external
then cmake works perfectly.
